export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_FAILURE = 'EDIT_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';

export const DELETE_REQUEST = 'DELETE_REQUEST';