---
- name: Create bash profile
    shell: "touch .bash_profile"

- name: Add a variable to the server shell
    lineinfile:
      dest: "{{ home }}/.bash_profile"
      regexp: "^ENV_VAR= "
      line: "ENV_VAR={{ variavel }}"
    become: no

- name: Get the value of a variable
    shell: ". {{ home }}/.bash_profile && echo $ENV_VAR"
    register: foo

- debug: msg="Variavel = {{ foo.stdout }}"
