n = input('Digite um numero de 0 a 9999: ')
# print(f'Unidade {s[-1]}')
# print(f'Dezena {s[-2]}')
# print(f'Centena {s[-3]}')
# print(f'Milhar {s[-4]}')
n = n.rjust(4, "0")
print(f'Unidade{n[0]}')
print(f'Unidade{n[1]}')
print(f'Unidade{n[2]}')
print(f'Unidade{n[3]}')
