# Instalando Apache no Ubuntu e no CentOs
---
- name: Install Apache
  hosts: all
  become: yes
  vars:
    variavel: teste
    home: /home/ubuntu

  handlers:
    - import_tasks: handlers/apache.yml

  pre_tasks:
    - name: Load variable files
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yml"
        - "vars/apache_default.yml"

  tasks:
    - import_tasks: tasks/apache.yml

# - import_playbook: teste.yml
