---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ add_packages }}"

- name: Remove packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ rem_packages }}"

- import_tasks: uptime.yml
