version: '3.1'

services:

  db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    container_name: adminer_mysql
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
