# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: postgre_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    container_name: adminer_posgre
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

