version: '3.1'

services:

  db:
    container_name: maria_db
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    container_name: adminer_maria
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

