# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine312"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "128"
    vb.linked_clone = true
  end

  # App server 1
  config.vm.define "alp1" do |app|
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip: "192.168.60.10" 
  end

  # App server 2
  config.vm.define "alp2" do |app|
    app.vm.hostname = "orc-app2.test"
    app.vm.network :private_network, ip: "192.168.60.11" 
  end

  # App server 3

  config.vm.define "alp3" do |app|
    app.vm.hostname = "orc-app3.test"
    app.vm.network :private_network, ip: "192.168.60.12" 
  end

end
